version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
    permissions:
      - object: /
        pattern: "**"
        owner: ec2-user
        group: ec2-user
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: ec2-user
